language: objective-c
osx_image: xcode7
xcode_project: LFNetworkReachability/LFNetworkReachability.xcodeproj
xcode_scheme: LFNetworkReachability

script:
- xctool -project LFNetworkReachability/LFNetworkReachability.xcodeproj -scheme LFNetworkReachability build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
